In [1]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\kapab\onedrive\desktop\kedrolabs\venv\lib\site-packages (1.7.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy>=1.22.0 in c:\users\kapab\onedrive\desktop\kedrolabs\venv\lib\site-packages (from scikit-learn) (2.3.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\kapab\onedrive\desktop\kedrolabs\venv\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\kapab\onedrive\desktop\kedrolabs\venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\kapab\onedrive\desktop\kedrolabs\venv\lib\site-packages (from scikit-learn) (3.6.0)

In [2]:
%load_ext kedro.ipython

[09/11/26 17:43:48] INFO     Using                                                                  ]8;id=682259;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=738061;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\framework\project\__init__.py#270\270]8;;\
                             'c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedr
                             o\framework\project\rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=499028;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=760522;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#63\63]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=77975;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=70828;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#65\65]8;;\

                    INFO     Resolved project path as:                                              ]8;id=115101;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=462116;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#180\180]8;;\
                             c:\Users\kapab\OneDrive\Desktop\KedroLabs\spaceflights.
                             To set a different path, run '%reload_kedro <project_root>'

[09/11/26 17:43:57] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=778996;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=222519;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro_telemetry\plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`
                             environment variables, or create a `.telemetry` file in the current
                             working directory with the contents `consent: false`. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

                    INFO     Kedro project spaceflights                                             ]8;id=314510;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=93033;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=929826;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=634745;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\
                             'pipelines'

[09/11/26 17:43:58] INFO     Registered line magic 'run_viz'                                        ]8;id=629824;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=656164;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\ipython\__init__.py#153\153]8;;\

In [4]:
df = catalog.load("model_input_table")

[09/11/26 17:44:11] INFO     Loading data from model_input_table (ParquetDataset)...           ]8;id=903648;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=441915;file://c:\Users\kapab\OneDrive\Desktop\KedroLabs\venv\Lib\site-packages\kedro\io\data_catalog.py#1046\1046]8;;\

In [5]:
df.head()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True

In [6]:
features = ["engines", "passenger_capacity", "crew","d_check_complete", "moon_clearance_complete", "iata_approved","company_rating","review_scores_rating"]

In [7]:
X = df[features]
y = df["price"]

In [8]:
X.head()

,engines,passenger_capacity,crew,d_check_complete,moon_clearance_complete,iata_approved,company_rating,review_scores_rating
0,2.0,4,2.0,False,False,False,100.0,91.0
1,3.0,5,3.0,False,False,True,100.0,96.0
2,1.0,2,1.0,True,False,False,100.0,97.0
3,1.0,2,1.0,False,False,True,100.0,95.0
4,5.0,10,5.0,False,False,True,100.0,97.0

In [9]:
y.head()

0    1715.0
1    3405.0
2    1806.0
3    1676.0
4    4718.0
Name: price, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2)

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()
model

LinearRegression()

In [14]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
pred_lr = model.predict(X_test)

In [18]:
# Random Forest
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)

In [19]:
# Gradient Boosting
gb = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)
gb.fit(X_train, y_train)
pred_gb = gb.predict(X_test)

In [21]:
from sklearn.metrics import r2_score

print("Linear Regression R²:", r2_score(y_test, pred_lr))
print("Random Forest R²:", r2_score(y_test, pred_rf))
print("Gradient Boosting R²:", r2_score(y_test, pred_gb))

Linear Regression R²: 0.3897314256851915
Random Forest R²: 0.42315768379485297
Gradient Boosting R²: 0.4365679459265954